image: docker:stable

stages:
  - compile
  - package

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

cache:
  paths:
    - .m2/repository/
    - ljprojectbuilder/target/
   
compile_java:
  stage: compile
  image: maven:3.3.9-jdk-8  
  script:
    - echo "building war"
    - 'cd ljprojectbuilder'
    - 'mvn clean package'
  only:
    - master
  artifacts:
    paths:
    - ljprojectbuilder/target/ljprojectbuilder.war

package_tomee:
  stage: compile
  image: maven:3.3.9-jdk-8
  script:
    - echo "building tomee"
    - 'cd tomee'
    - 'mvn tomee:build'
  only:
    - master
  artifacts:
    paths:
    - tomee/target/apache-tomee

package_docker:
  stage: package
  script:
    - docker build -t ljprojectbuilder .  

 