
name: Java CI with Maven

on:
  push:
    branches: [ spring-boot ]
  pull_request:
    branches: [ spring-boot ]

jobs:
  build:
    name: "Building project with Java 14"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Build with Maven
      run: mvn -B package -Pfrontend --file spring/pom.xml
    - name: Upload Maven build artifact
      uses: actions/upload-artifact@v1
      with:
        name: artifact
        path: spring/application/target/application-0.0.1-SNAPSHOT.jar
    - name: Build Docker container
      uses: whoan/docker-build-with-cache-action@v5
      with:
        username: "${{ secrets.DOCKER_USERNAME }}"
        password: "${{ secrets.DOCKER_PASSWORD }}"        
        image_name: ljprojectbuilder
        image_tag: latest
        registry: docker.pkg.github.com
        context: spring
